[build]
 publish = "."
 command = "node javascript/generate-sitemap.js"
 functions = "netlify/functions"
 ignore_secrets = ["SUPABASE_ANON_KEY"]

[dev]
 command = ""
 targetPort = 8888
 framework = "#static"
 autoLaunch = true
 edge_functions = false

[build.environment]
 SECRETS_SCAN_OMIT_KEYS = "SUPABASE_ANON_KEY"
 NODE_VERSION = "22"

[[redirects]]
 from = "/account"
 to   = "/account/orders"
 status = 301

[[redirects]]
 from = "/*.html"
 to   = "/:splat"
 status = 301